### ISSUE TITLE
引用库失效

### ISSUE THREAD

**Issue by command-z-z** [lixy123/TTGO_T_Watch_Baidu_Rec#1]
引用库失效了：https://github.com/lewisxhe/lvgl
能否提供下下载包，非常感谢！
邮箱:2383535943@qq.com

**Comment by lixy123** [comment]
底层支撑库版本升级后已无法编译，下载包我自已也找不到了。
需要用最新的底层库重写，现在太忙，暂时没空整理, 抱歉。

**Comment by lixy123** [comment]
如果你只是对语音转文字有兴趣的话，可以参考下此项目的源码：
https://github.com/lixy123/LilyGo-EPD47-MIC-TXT
